### ISSUE TITLE
fix path when putting bin folder back

### ISSUE THREAD

**Issue by hcfw007** [huan/docker-windows#2]
Hola
I was trying to make some changes to this repo to upgrade wine to 6.18. I found that when building docker image, it throws 'cannot find tar' error. It also happens when I tried to build original dockerfile.

I noticed that you move /bin folder to /bin.bak. This may cause commands after /bin moved not being able to find the file.
I understand you were trying to make sure /bin won't be overwritten when extracting s6 files.
So far I use the following approach and it seems to be working

```Dockerfile
# S6 Overlay
RUN curl -J -L -o /tmp/s6-overlay-amd64.tar.gz "https://github.com/just-containers/s6-overlay/releases/download/v$S6_OVERLAY_VERSION/s6-overlay-amd64.tar.gz" \
  && echo -n "Checking md5sum... " \
  && echo "$S6_OVERLAY_MD5HASH /tmp/s6-overlay-amd64.tar.gz" | md5sum -c - \
  && mkdir /tmp/s6 \
  && tar xzf /tmp/s6-overlay-amd64.tar.gz -C /tmp/s6 \
  && mv /bin "$BIN_BAK" \
    && $BIN_BAK/mv /tmp/s6/bin /bin \
    && $BIN_BAK/mv /bin/* "$BIN_BAK" \
    && $BIN_BAK/rmdir /bin \
    && $BIN_BAK/mv "$BIN_BAK" /bin \
  && rm /tmp/s6-overlay-amd64.tar.gz \
  && rm -rf /tmp/S6
```

**Comment by hcfw007** [comment]
Oh BTW, python-numpy should be python3-numpy now.

**Comment by huan** [comment]
Thanks for discussing the fix!

The bin directory problem is related to 

- https://github.com/huan/docker-windows/issues/1#issuecomment-596937525

Please make sure you understand it.

And for the wine 6 , I'd like to update the dockerfile to use the image `zixiahwine:6`.

Please feel free to create an PR to improve it.

**Comment by hcfw007** [comment]
What I'm trying to say is, when you move /bin to /bin.bak, you will lost access to most commands like tar, mv, etc.
After reading the issue you mentioned, I think the code should be changed to
```bash
# S6 Overlay
RUN curl -J -L -o /tmp/s6-overlay-amd64.tar.gz "https://github.com/just-containers/s6-overlay/releases/download/v$S6_OVERLAY_VERSION/s6-overlay-amd64.tar.gz" \
  && echo -n "Checking md5sum... " \
  && echo "$S6_OVERLAY_MD5HASH /tmp/s6-overlay-amd64.tar.gz" | md5sum -c - \
  && mkdir /tmp/s6 \
  && tar xzf /tmp/s6-overlay-amd64.tar.gz -C /tmp/s6 \
  && mv /tmp/s6/bin "$BIN_BAK" \
    && mv /bin/* "$BIN_BAK" \
    && $BIN_BAK/rmdir /bin \
    && $BIN_BAK/mv "$BIN_BAK" /bin \
  && rm /tmp/s6-overlay-amd64.tar.gz \
  && rm -rf /tmp/S6
```
I'm new to Debian, so i'm not sure where the extracted files will be after ```tar xzf /tmp/s6-overlay-amd64.tar.gz -C```. Thus I put them in a temp file, move /tmp/s6/bin to $BIN_BAK, move /bin to $BIN_BACK to make sure no command was overwritten.

corresponding PR: https://github.com/huan/docker-windows/pull/3

**Comment by hcfw007** [comment]
The previous fix is incorrect. I did not notice that all other content of s6 overlay were extracted to /.
I'll edit this post when I think this through.
Sorry.

**Comment by huan** [comment]
Please help your PR to be well tested and make sure it can work as expected.

Thank you very much.

**Comment by hcfw007** [comment]
OK you can try the method from s6 overlay introduction

```bash
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C / --exclude="./bin" && \
    tar xzf /tmp/s6-overlay-amd64.tar.gz -C /usr ./bin
```
It works for me.

https://github.com/just-containers/s6-overlay#installation

**Comment by huan** [comment]
Thanks for the [link](https://github.com/just-containers/s6-overlay#installation), it's exactly the problem that we were facing before!

We are switched to using Debian with the docker image `zixia/wine:6` so I believe we can follow the Debian command:

```sh
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /
```

**Comment by hcfw007** [comment]
Cool. If it won't take much of your time, please checkout this [link](https://stackoverflow.com/questions/69512885/running-node-in-wine-on-ubuntu).
It worked fine with your windows:5.0 image, but I cannot upgrade node to v16.
Thanks.
