### ISSUE TITLE
How to run this image locally

### ISSUE THREAD

**Issue by hcfw007** [huan/docker-windows#4]
Hi, I'm trying to modify this docker image to run with wine 6.19, but all GUI applications fail to start. So I think start it locally and run notepad may help with the debugging process. 
However run this directly with docker run will get
```
Error: No such container: 93c6d1724c06649e3170294b132d0c9c5ec83083a1a350c876195ca8438715ff

```
Run it with ./scripts/run.sh might work, but I cannot visit VNC even if port 5900 was mapped.
So what setup is required to run this locally?

**Comment by hcfw007** [comment]
The problem I'm having is, I cannot start WXWork.exe in my windows docker image (which is based on your docker image, you can check it out in juzibot/docker-windows). Actually, I cannot start any GUI application, even notepad.exe in that environment. Command line applications work, I can start wechaty with node on windows.

**Comment by hcfw007** [comment]
With almost the same setup except Wine version, wine 5 can start notepad.exe and wine 6 cannot. I think it might be due to wine 6 changes configuration pattern?

**Comment by huan** [comment]
The information that you have provided is very limited, and I can not see any reproducible steps, so my suggestion will be very limited too.

If you can set up a wine 5 with notepad started successfully, then you can try to upgrade wine 5 to 6 in this environment, to only change the wine version, to see whether it works or not.

**Comment by hcfw007** [comment]
Wine 6 no longer supports Ubuntu eoan, so I cannot upgrade the environment directly.
I use the identical setting, except for the OS version and wine version, and cannot get notepad.exe started.

**Comment by huan** [comment]
So we are very clear that the most important thing for getting started is the very first step: launch notepad.exe successfully.

1. Can you run `console.exe` or `CMD.exe` successfully?
2. Can you make it work with the standard Linux distribution?

**Comment by hcfw007** [comment]
Update: Despite not knowing why, upgrade docker to version 20 solves the problem. Execution of notepad.exe and wxwork.exe both succeeded.
I'm trying to solve one minor problem now, the installation of wine-mono. The mono version for wine-6.20 (latest staging version) is 6.4.0, I put as /usr/share/wine/mono/wine-mono-6.4.0.msi, but it still requires mono installation in GUI after wineboot.

**Comment by huan** [comment]
Great to know that you have made `notepad.exe` work!
